// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.convoar {
    public class VersionInfo {
        public static string appVersion = "2.0.2";
        public static string longVersion = "2.0.2-20220503-1f9e2600";
        public static string buildDate = "20220503";
    }
}
